{
 "title": "Redmine Monitoring(192.168.2.170)",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Redmine Running Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 21, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "probe_success{instance=\"http://redmine-mo.local\",job=\"blackbox_http\"}"
    }
   ]
  },
  {
   "title": "Container Count",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(container_start_time_seconds{id=~\"/docker/.*\"})"
    }
   ]
  },
  {
   "title": "The moment you drop the needle on the record",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "probe_success{instance=\"http://redmine-mo.local\",job=\"blackbox_http\"}"
    }
   ]
  },
  {
   "title": "Node CPU Core",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "machine_cpu_cores" }
   ]
  },
  {
   "title": "Node CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 4, "y": 9 },
   "targets": [
    {
     "expr": "(rate(node_cpu_seconds_total{mode=\"iowait\"}[5m]) + on(job)rate(node_cpu_seconds_total{mode=\"system\"}[5m]) + on(job)rate(node_cpu_seconds_total{mode=\"user\"}[5m]) )*100"
    }
   ]
  },
  {
   "title": "Redmine CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{name=~\"^redmine_redmine_.\"}[5m])*100",
     "legendFormat": "redmine"
    },
    {
     "expr": "rate(container_cpu_usage_seconds_total{name=~\"^redmine_mysql_.\"}[5m])*100",
     "legendFormat": "mysql"
    },
    {
     "expr": "rate(container_cpu_usage_seconds_total{name=~\"^nginx_proxy_.\"}[5m])*100",
     "legendFormat": "nginx_proxy"
    }
   ]
  },
  {
   "title": "Node Total Memory",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 18 },
   "format": "mbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "machine_memory_bytes{group=\"docker-container\", instance=\"192.168.2.170:8080\", job=\"cAdvisor\"} /1000000"
    }
   ]
  },
  {
   "title": "Node Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 18 },
   "targets": [
    {
     "expr": "node_memory_Active_bytes{group=\"docker-host\"} / ignoring(group,instance,job) machine_memory_bytes{group=\"docker-container\"}*100"
    }
   ]
  },
  {
   "title": "Redmine Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name=~\"^redmine_redmine_.\"}",
     "legendFormat": "redmine"
    },
    {
     "expr": "container_memory_usage_bytes{name=~\"^redmine_mysql_.\"}",
     "legendFormat": "mysql"
    },
    {
     "expr": "container_memory_usage_bytes{name=~\"^nginx_proxy_.\"}",
     "legendFormat": "nginx_proxy"
    }
   ]
  }
 ]
}